package com.clinic.c46.ExaminationFlowService.application.saga;

public enum ClinicWorkFlowProcessingStateMachine {
    MEDICAL_FORM_CREATED,
    PENDING_CREATE_INVOICE,
    INVOICE_CREATED,
    PENDING_CREATE_EXAMINATION,
    EXAMINATION_CREATED,
    PENDING_CREATE_QUEUE_ITEM,
    QUEUE_ITEM_CREATED,
    PENDING_PROCESS_QUEUE_ITEM,
    QUEUE_ITEM_PROCESSED,
    PENDING_PAYMENT,
    MEDICAL_FORM_COMPLETED,
    EXAMINATION_COMPLETED,
    COMPLETED,
    FAILED,
}
