package com.clinic.c46.ExaminationFlowService.application.saga;

public enum ExamWorkFlowProcessingStateMachine {
    TAKE_ITEM_REQUEST_RECEIVED, PENDING_DEQUEUE, DEQUEUED, PENDING_SEND_ITEM, ITEM_SENT, ITEM_PROGRESSED, PENDING_CREATE_RESULT, RESULT_CREATED, RESULT_SIGNED, COMPLETED
}
